export enum QueryTrigger {
  WHAT_TO_DO = 'WHAT_TO_DO',
}

export enum ConversationId {
  REGISTRATION = 'REGISTRATION',
  CODE_WORD_INPUT = 'CODE_WORD_INPUT',
  STUDENT_PUNISHMENT = 'STUDENT_PUNISHMENT',
}
